name: DOCKER-CI

# Trigger the workflow on push to master
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout
      uses: actions/checkout@v3

      - name: Login to the container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/stats-now
        tags: latest
      
      - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}


